default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: mypassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: team_management_app_development

test:
  <<: *default
  database: team_management_app_test

production:
  <<: *default
  database: team_management_app_production
  username: team_management_app
  password: <%= ENV["TEAM_MANAGEMENT_APP_DATABASE_PASSWORD"] %>
